# 开发环境配置

# 数据源配置
spring:
  datasource:
#    url: jdbc:mysql://47.108.231.185:3306/erp?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
#    username: erp
#    password: EcYKmAJs5TSwWEzi

    url: jdbc:mysql://localhost:3306/country?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  boot:
    admin:
      client:
        url: http://localhost:8888 #配置admin-server地址


# 日志配置
logging:
  level:
    com.mt: DEBUG
    com.baomidou.mybatisplus: DEBUG


jeecg :
  # local|minio|alioss
  uploadType: local
  # local
  path:
    #文件路径
    upload: /report/upload
  jmreport:
    #数据字典是否进行saas数据隔离(限制只能看自己的字典)
    saas: false
    #是否自动保存
    autoSave: true
    #自动保存间隔时间毫秒
    interval: 20000
    # 列索引
    col: 100
    #自定义项目前缀
    customPrePath:
    # 自定义API接口的前缀 #{api_base_path}的值
    apiBasePath: http://localhost:8080/jeecg-boot
    #数据源标识
    datasource: master
    #预览分页自定义
    pageSize:
      - 10
      - 20
      - 30
      - 40
    #打印纸张自定义
    printPaper:
      - title: A5纸
        size:
          - 148
          - 210
      - title: B4纸
        size:
          - 250
          - 353
    #接口超时设置（毫秒）
    connect-timeout: 300000
    #Excel导出模式(fast/快、primary/精致模式，默认fast)
    export-excel-pattern: fast
    #Excel导出数据条数，超过10000条不带样式导出
    page-size-number: 10000
    #预览页面的工具条 是否显示 默认true
    viewToolbar: true
    #设计页面表格的线是否显示 默认true
    line: true


