# 开发环境配置

simple:
  workspapce: D:\\my_project\\country\\workSpace
# erp
#  serverPath: ${workspapce}\\erp-boot\\erp
#  lis
  serverPath: ${workspapce}\\DDD5\\ems
  uiPath: ${workspapce}\\DDD5_UI
  codeTablesFile: ${serverPath}\\src\\main\\resources\\codetables.json
  moduleFile: ${serverPath}\\src\\main\\resources\\modules.json
  velocityTemplate: ${workspapce}\\DDD5\\generate\\src\\main\\resources
#  velocityTemplate: ${workspapce}\\erp-boot\\generate\\src\\main\\resources
  exceptionLogPath: D:\\BusinessException
  uploadFileAddress: D:\\spring_files
  staticFilePath: D:\\DDDFile\\
  staticOthFilePath: D:\\DDDOthFile\\
  bigScreen: ${workspapce}\\erp-bs\\src



  applicationName: 框架
  applicationCode: DDD4
  shortCode: DD
  basePackage: com.mt
  src: src\\
  charset_UTF8: UTF-8
  charset_ISO: ISO-8859-1
  dataBase: mysql
  serverId: app1
  logPath: d:\\BusinessException\\
  isDeveloping: true
  whiteURLs: /favicon.ico, /api/file/**,/api/actuator/**,/actuator/**,/,/assets/**,/**.html,/api/login,/error,/druid/**,/webjars/**,/swagger-ui.html,/swagger-resources/**,/v2/api-docs,/jmreport/**,/api/qr/**,/api/lis/modelDesign/**,/api/erp/trans/Driver/signIn

  # token过期时间,单位为分钟
  tokenExpireTime: 3000
  #token将要过期自动刷新,单位分钟
  tokenWillExpireTime: 30
